### ISSUE TITLE
Remplacer les éléments mentionnant "wootook" par "uniguerre"

### ISSUE THREAD

**Issue by kiwille** [kiwille/uniguerre#10]
Il faudrait remplacer les mots, images, logo (favicon par ex.) qui mentionne "Wootook" par celle de "Uniguerre".

**Comment by mandalorien** [comment]
il n'y a plus que le logo apparement , j'ai vérifié partout ^^'

**Comment by kiwille** [comment]
Ok merci, s'il reste que ca à faire, je clos l'issue et j'en créé une spécifiquement pour la création d'un logo.
