### ISSUE TITLE
Il est possible de se connecter même en ayant saisit un mauvais mot de passe

### ISSUE THREAD

**Issue by kiwille** [kiwille/uniguerre#15]
Si le mot de passe est incorrect, on peut quand même se connecter.

**Comment by boermansjo** [comment]
Bizzare, chez moi ça fonctionne comme il faut : 
![mdpincorrect](https://user-images.githubusercontent.com/582664/29131340-e268caa2-7d2c-11e7-8647-7139de67a0c2.PNG)

**Comment by kiwille** [comment]
Tiens tu as encore le projet ? :)

Alors ça c'est bien étonnant que ca ne se produit pas chez toi.

**Comment by mandalorien** [comment]
je suis moi même surpris que le projet est toujours en cours ^^

**Comment by boermansjo** [comment]
Surprise ~!~
Sinon, on continu sur ce projet ou pas ? Depuis le temps j'ai plus suivis si il y a des nouveaux clones d'ogame...

**Comment by mandalorien** [comment]
Pour ma part je dirai pas non , pour me remettre dans le bain , par contre quels sont les nouveaux clone d'ogame ?

**Comment by kiwille** [comment]
En fait, le projet était bien en arrêt, mais j'ai un pote qui voulait que je continue... 😅

**Comment by kiwille** [comment]
Bon j'ai toujours ce problème de login, je vais m'y coller pour comprendre ce qui se passe...

**Comment by boermansjo** [comment]
Ça reste bizarre.

**Comment by kiwille** [comment]
```php
        $us = self::selectAll();
        foreach ($us as $u) {
            if (strtolower($u->username) == strtolower($username) || 
                strtolower($u->hash_password) == strtolower($hashPassword)) {
                return $u;
            }
        }
        return null;
```

Retourner l'utilisateur selon si son pseudo OU son mot de passe est correcte me parait bien suspect :p

**Comment by kiwille** [comment]
J'ai pu constater un problème dans la comparaison entre le hash du mot de passe saisie et celle de la base de données.
Les hash sont différents tout le temps, et impossible de comparer avec la méthode actuellement utilisée. 
Mais il y a une méthode en php qui permet toutefois de faire les choses bien: `password_hash` et `password_verify`.

```php
$options = [
    'cost' => 11,
    'salt' => mcrypt_create_iv(22, MCRYPT_DEV_URANDOM),
];
$hash = password_hash("rasmuslerdorf", PASSWORD_BCRYPT, $options);

var_dump($hash);
var_dump(password_verify("rasmuslerdorf", $hash));
```

En revanche, je doute que nos mots de passe actuels soient encore bon après la mise à jour que je compte faire passer alors il faudra surement la modifier en base de données.

@mandalorien @boermansjo

**Comment by kiwille** [comment]
C'est résolu. Je n'ai pas eu besoin de changer les mots de passes en base de données.
