### ISSUE TITLE
Images manquantes dans l'interface du chat

### ISSUE THREAD

**Issue by kiwille** [kiwille/uniguerre#28]
Les images dans le chat sont cassées à priori:

![image](https://user-images.githubusercontent.com/1839523/31467835-b1f57e5c-aedb-11e7-853e-05a7c4182714.png)

**Comment by boermansjo** [comment]
C'est le jeu local que tu fais tourné ? J'ai essayer hier de faire tourné la branche 'DEV' mais sans succès.
La page index.php charge a l'infini. Il faut une version spécifique de php ?

**Comment by kiwille** [comment]
Mon jeu est en local, j'utilise la configuration suivante:
- Apache v. 2.4.23
- PHP 5.6.25
- MySql 5.7.14

Je vais essayer en utilisant PHP 7 pour voir ce que cela donne.
