### ISSUE TITLE
Compatibilité avec PHP 7 incertaine

### ISSUE THREAD

**Issue by kiwille** [kiwille/uniguerre#30]
@boermansjo : #28 

> J'ai essayer hier de faire tourné la branche 'DEV' mais sans succès.
> La page index.php charge a l'infini. J'utilise Wampserver 3.0... ça risque d’être un problème non si le jeu  fonctionne pas avec php 7...

**Comment by kiwille** [comment]
Le jeu a été concu avec la configuration suivante :

Apache v. 2.4.23
PHP 5.6.25
MySql 5.7.14

La comptabilité avec PHP 7 ne serait pas garanti à priori. Cela doit être corrigé.

**Comment by kiwille** [comment]
Tu feras un pull de la branche "dev" et tu pourras me confirmer que c'est corrigé?

**Comment by boermansjo** [comment]
Ok je vais regarder ça ce soir.
C'est possible que mon wampserver merde :p
